"""Update models to match current schema
Revision ID: 1e025f228445
Revises: 20231115
Create Date: 2025-11-09 07:45:03.100581
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e025f228445'
down_revision = '20231115'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paddle_product_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('subscription', 'one_time', name='producttype'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('credits_included', sa.Integer(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('free', 'pro', 'enterprise', name='subscriptiontier'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paddle_product_id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('paddle_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paddle_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('paddle_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('credits_added', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paddle_transaction_id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.add_column('jobs', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('jobs', sa.Column('pdf_s3_url', sa.String(length=1000), nullable=True))
    op.add_column('jobs', sa.Column('audio_s3_url', sa.String(length=1000), nullable=True))
    op.add_column('jobs', sa.Column('progress_percentage', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('voice_provider', sa.Enum('openai', 'google', 'aws_polly', 'azure', 'eleven_labs', name='voiceprovider'), nullable=True))
    op.add_column('jobs', sa.Column('voice_type', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('reading_speed', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('include_summary', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('conversion_mode', sa.Enum('full', 'summary_explanation', name='conversionmode'), nullable=True))
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'pdf_s3_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('auth_provider_id', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('subscription_tier', sa.Enum('free', 'pro', 'enterprise', name='subscriptiontier'), nullable=True))
    op.add_column('users', sa.Column('paddle_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('one_time_credits', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('monthly_credits_used', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_auth_provider_id'), 'users', ['auth_provider_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_users_auth_provider_id'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'monthly_credits_used')
    op.drop_column('users', 'one_time_credits')
    op.drop_column('users', 'paddle_customer_id')
    op.drop_column('users', 'subscription_tier')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'auth_provider_id')
    op.alter_column('jobs', 'pdf_s3_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('jobs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'created_at')
    op.drop_column('jobs', 'conversion_mode')
    op.drop_column('jobs', 'include_summary')
    op.drop_column('jobs', 'reading_speed')
    op.drop_column('jobs', 'voice_type')
    op.drop_column('jobs', 'voice_provider')
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'progress_percentage')
    op.drop_column('jobs', 'audio_s3_url')
    op.drop_column('jobs', 'pdf_s3_url')
    op.drop_column('jobs', 'original_filename')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
